Arya game
aryanagarkar/MathGame pull request #3
Opened 2020-09-24 22:21 UTC by aryanagarkar

2020-09-24 22:31 UTC, nagarkar requested changes

2020-09-24 22:31 UTC, nagarkar commented on HasseGraph/service/Graph.cs
> +        List<GraphLink> links = new MList<GraphLink>();
Why isn't this readonly?

2020-09-24 22:31 UTC, nagarkar commented on HasseGraph/service/Graph.cs
> +        public Graph(MDictionary<string, GraphNode> idNodeMap, List<GraphLink> links)
Why is this public?

2020-09-24 22:31 UTC, nagarkar commented on HasseGraph/service/Graph.cs
> +        public  List<GraphLink> Links{
Please format all files. I see needless spaces and lack of spaces etc.

2020-09-24 22:31 UTC, nagarkar commented on HasseGraph/service/GraphBuilder.cs
> +        MDictionary<string, GraphNode> idNodeMap = new MDictionary<string, GraphNode>();
Should these be private or is private the default?

2020-09-24 22:31 UTC, nagarkar commented on HasseGraph/service/GraphBuilder.cs
> +        GraphBuilder(List<GraphLink> links, MDictionary<string, GraphNode> idNodeMap){
Why do you need this?

2020-09-24 22:31 UTC, nagarkar commented on HasseGraph/service/GraphBuilder.cs
> +            links.Add(new GraphLink(nodeId1, nodeId2));
What if this link is already present? Where are you checking you don't add it twice?

2020-09-24 22:31 UTC, nagarkar commented on HasseGraph/service/GraphBuilder.cs
> +        public Graph build(){
Public methods at top, private at bottom.

2020-09-24 22:31 UTC, nagarkar commented on HasseGraph/service/GraphLink.cs
> +        GraphNode source;
ditto question

2020-09-24 22:31 UTC, nagarkar commented on HasseGraph/service/GraphNode.cs
> +            incomingLinks = new MList<GraphNode>();
I don't see an MList class defined anywhere.

2020-09-24 23:46 UTC, aryanagarkar commented on HasseGraph/service/Graph.cs
> +        List<GraphLink> links = new MList<GraphLink>();
Changed this to read-only.

2020-09-24 23:51 UTC, aryanagarkar commented on HasseGraph/service/Graph.cs
> +        public  List<GraphLink> Links{
Formatted all the files.

2020-09-24 23:52 UTC, aryanagarkar commented on HasseGraph/service/GraphBuilder.cs
> +        MDictionary<string, GraphNode> idNodeMap = new MDictionary<string, GraphNode>();
If you don't specify, these are private by default.

2020-09-24 23:55 UTC, aryanagarkar commented on HasseGraph/service/GraphBuilder.cs
> +        GraphBuilder(List<GraphLink> links, MDictionary<string, GraphNode> idNodeMap){
I changed the other code and I didn't need this but I forgot to delete it. I deleted it.

2020-09-25 00:09 UTC, aryanagarkar commented on HasseGraph/service/GraphBuilder.cs
> +            links.Add(new GraphLink(nodeId1, nodeId2));
I changed the code to check if the link is already present.

2020-09-25 00:12 UTC, aryanagarkar commented on HasseGraph/service/GraphNode.cs
> +            incomingLinks = new MList<GraphNode>();
I forgot to commit that class, I will commit it in the next commit.

2020-09-25 00:14 UTC, aryanagarkar commented on HasseGraph/service/GraphBuilder.cs
> +        public Graph build(){
I fixed all the files too have public methods on top, and private on the bottom.

2020-09-25 00:22 UTC, aryanagarkar commented on HasseGraph/service/Graph.cs
> +        public Graph(MDictionary<string, GraphNode> idNodeMap, List<GraphLink> links)
If I make all of these classes private, I will need to put them into nested classes and one file would become huge. I am going to try to make it internal instead.

2020-09-25 00:23 UTC, aryanagarkar commented on HasseGraph/service/GraphLink.cs
> +        GraphNode source;
If I make all of these classes private, I will need to put them into nested classes and one file would become huge. I am going to try to make it internal instead.

2020-10-01 21:48 UTC, closed without merging