Game
aryanagarkar/MathGame pull request #7
Opened 2020-11-05 20:46 UTC by aryanagarkar

2020-11-06 03:30 UTC, nagarkar requested changes

2020-11-06 03:30 UTC, nagarkar commented on ConsoleApps/ConsoleAppReadme.md
> +You need to have visual studio code installed.
Supported Platforms

2020-11-06 03:30 UTC, nagarkar commented on ConsoleApps/HasseGraph/service.Tests/GraphAnalysisTests.cs
> +            expected.Add(graph.IdNodeMap[conceptA]);
expected should not data being tested.

2020-11-06 03:30 UTC, nagarkar commented on ConsoleApps/HasseGraph/service.Tests/GraphAnalysisTests.cs
> +            Graph<Concept> graph = new Graph<Concept>.Builder()
what's wrong here?

2020-11-06 03:30 UTC, nagarkar commented on ConsoleApps/HasseGraph/service.Tests/GraphAnalysisTests.cs
> +                    .addLink(conceptA, conceptB)
ditto

2020-11-06 03:30 UTC, nagarkar commented on ConsoleApps/HasseGraph/service.Tests/GraphBuilderTests.cs
> +            .OutgoingLinks.Contains(conceptC));
formatting

2020-11-06 03:30 UTC, nagarkar commented on ConsoleApps/HasseGraph/service.Tests/LearningSpaceTests.cs
> +            List<Concept> actual = L.getRecentlyLearnedConcepts();
List<Concept> actualRecentlyLearnt = L.getRecentlyLearnedConcepts();

            //Expectations
            List<Concept> expected = new List<Concept>();
            expected.Add(conceptB);

            //Test and assert
            Assert.IsTrue(actualRecentlyLearnt.SequenceEqual(expected));

2020-11-06 03:30 UTC, nagarkar commented on ConsoleApps/HasseGraph/service.Tests/LearningSpaceTests.cs
> +            LearningSpace L = new LearningSpace.Builder()
These are very simple graphs.

2020-11-06 03:30 UTC, nagarkar commented on ConsoleApps/HasseGraph/service/Graph/Graph.cs
> +    public class Graph<T>
At least a class level comment describing usage

2020-11-06 03:30 UTC, nagarkar commented on ConsoleApps/HasseGraph/service/Graph/GraphAnalysis.cs
> +        public List<GraphNode<T>> topologicalSort()
WHat is this doing?

2020-11-06 03:30 UTC, nagarkar commented on ConsoleApps/HasseGraph/service/Graph/GraphAnalysis.cs
> +            }
return sortedNodes == null;

2020-11-06 03:30 UTC, nagarkar commented on ConsoleApps/HasseGraph/service/Graph/GraphAnalysis.cs
> +        readonly List<GraphNode<T>> sortedNodes;
what does 'null value mean?

2020-11-06 03:30 UTC, nagarkar commented on ConsoleApps/HasseGraph/service/Graph/GraphNode.cs
> +            GraphNode<T> node = (GraphNode<T>)obj;
(GraphNode<T>) obj;

2020-11-06 03:30 UTC, nagarkar commented on ConsoleApps/HasseGraph/service/LearningSpace.cs
> +        public List<KnowlegeState> setUpAndgeneratePossibleStates()
setupAndGenerate..

2020-11-06 03:30 UTC, nagarkar commented on ConsoleApps/HasseGraph/service/LearningSpace.cs
> +            Dictionary<Concept, int> np = new Dictionary<Concept, int>();
if using crappy variable names, explain in a comment.

2020-11-06 03:30 UTC, nagarkar commented on ConsoleApps/HasseGraph/service/LearningSpace.cs
> +            foreach (GraphNode<Concept> node in graph.Nodes)
combine.

2020-11-06 03:30 UTC, nagarkar commented on ConsoleApps/HasseGraph/service/LearningSpace.cs
> +        private List<KnowlegeState> generatePossibleStates(List<KnowlegeState> L, KnowlegeState state,
Totally opaque code.

2020-11-06 03:30 UTC, nagarkar commented on ConsoleApps/HasseGraph/service/MainProgram.cs
> +            // Concept conceptA = new Concept("A");
?

2020-11-06 03:30 UTC, nagarkar commented on ConsoleApps/Story/service.Tests/SaveAndLoadStoryTests.cs
> +            // node.Character = character.ToString();
?

2020-11-06 17:26 UTC, aryanagarkar commented on ConsoleApps/HasseGraph/service.Tests/GraphAnalysisTests.cs
> +            expected.Add(graph.IdNodeMap[conceptA]);
I created graph nodes out of the concepts and added them to my list instead.

2020-11-06 17:35 UTC, aryanagarkar commented on ConsoleApps/HasseGraph/service.Tests/GraphBuilderTests.cs
> +            .OutgoingLinks.Contains(conceptC));
I formatted all the files.

2020-11-06 17:43 UTC, aryanagarkar commented on ConsoleApps/HasseGraph/service.Tests/LearningSpaceTests.cs
> +            List<Concept> actual = L.getRecentlyLearnedConcepts();
I changed all the names like this in all my tests to be more explanatory.

2020-11-06 17:48 UTC, aryanagarkar commented on ConsoleApps/HasseGraph/service/Graph/GraphAnalysis.cs
> +            }
Changed to "return sortedNodes == null;"

2020-11-06 17:53 UTC, aryanagarkar commented on ConsoleApps/HasseGraph/service/Graph/GraphNode.cs
> +            GraphNode<T> node = (GraphNode<T>)obj;
I formatted this and the other classes.

2020-11-06 17:54 UTC, aryanagarkar commented on ConsoleApps/HasseGraph/service/MainProgram.cs
> +            // Concept conceptA = new Concept("A");
This part is not doing anything so I took it out.

2020-11-06 17:58 UTC, aryanagarkar commented on ConsoleApps/Story/service.Tests/SaveAndLoadStoryTests.cs
> +            // node.Character = character.ToString();
I forgot to take this out. I was trying to do something and it worked and I forgot to take this out because I didn't need it. I took it out.

2020-11-06 18:22 UTC, aryanagarkar commented on ConsoleApps/HasseGraph/service/Graph/Graph.cs
> +    public class Graph<T>
I added class-level comments.

2020-11-06 18:31 UTC, aryanagarkar commented on ConsoleApps/HasseGraph/service/Graph/GraphAnalysis.cs
> +        public List<GraphNode<T>> topologicalSort()
I added comments for the methods in graph analysis.

2020-11-06 18:33 UTC, aryanagarkar commented on ConsoleApps/HasseGraph/service/Graph/GraphAnalysis.cs
> +        readonly List<GraphNode<T>> sortedNodes;
Added a comment here.

2020-11-06 18:36 UTC, aryanagarkar commented on ConsoleApps/HasseGraph/service/LearningSpace.cs
> +            foreach (GraphNode<Concept> node in graph.Nodes)
Combined these. Wrote:
foreach (GraphNode<Concept> node in graph.Nodes)
            {
                np.Add(node.Identity, node.IncomingLinks.Count);
                if (node.IncomingLinks.Count == 0)
                {
                    cs.Add(node.Identity);
                }
            }

2020-11-06 18:38 UTC, aryanagarkar commented on ConsoleApps/HasseGraph/service/LearningSpace.cs
> +        public List<KnowlegeState> setUpAndgeneratePossibleStates()
It's really "setUpAndGetPossibleStates". Changed it.

2020-11-06 18:52 UTC, aryanagarkar commented on ConsoleApps/ConsoleAppReadme.md
> +You need to have visual studio code installed.
Added a supported platforms section.

2020-11-08 03:19 UTC, aryanagarkar commented on ConsoleApps/HasseGraph/service.Tests/GraphAnalysisTests.cs
> +            Graph<Concept> graph = new Graph<Concept>.Builder()
Took out all the concepts that I was not using.

2020-11-08 03:23 UTC, aryanagarkar commented on ConsoleApps/HasseGraph/service.Tests/GraphAnalysisTests.cs
> +                    .addLink(conceptA, conceptB)
I did the same as I did above. I took out all the concepts that I was not using.

2020-11-08 03:39 UTC, aryanagarkar commented on ConsoleApps/HasseGraph/service/LearningSpace.cs
> +            Dictionary<Concept, int> np = new Dictionary<Concept, int>();
I renamed the variables to have descriptive names.

2020-11-11 23:38 UTC, aryanagarkar commented on ConsoleApps/HasseGraph/service/LearningSpace.cs
> +        private List<KnowlegeState> generatePossibleStates(List<KnowlegeState> L, KnowlegeState state,
Not opaque anymore. Added comments, changed variable names, and got it to work.

2020-11-12 18:53 UTC, aryanagarkar commented on ConsoleApps/HasseGraph/service.Tests/LearningSpaceTests.cs
> +            LearningSpace L = new LearningSpace.Builder()
I added a test with the graph from the paper (finally!) to learning space

2020-11-28 20:40 UTC, ritucjain commented on ConsoleApps/HasseGraph/service/MainProgram.cs
> -            // Concept conceptA = new Concept("A");
Why is all the code commented here? Where is this main called from?

2020-12-06 18:42 UTC, aryanagarkar commented on ConsoleApps/HasseGraph/service/MainProgram.cs
> -            // Concept conceptA = new Concept("A");
Dotnet run will call this main. However, if I take out the main class and do dotnet test. it gives the error that there has to be a main class as an entry point. I need the main class, but it won't have any code in it.

2021-01-02 22:07 UTC, closed without merging